services:

  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: haksan-minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: haksan-minio-dev

    volumes:
      - minio_data:/data
      - ./minio.license:/minio.license:ro

    command:
      - server
      - /data
      - --console-address
      - ":9001"
      - --license
      - /minio.license

volumes:
  minio_data: